apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  externalName: db.csiqjhriyqb7.us-east-1.rds.amazonaws.com
  selector:
    app: db
  type: ExternalName
status:
  loadBalancer: {}