---
apiVersion: v1
kind: Service
metadata:
  name: teatro-final-kubernetes
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: teatro-final-kubernetes